language: node_js
node_js:
  - "node"
cache:
  - yarn
install:
  - yarn install --no-optional
script:
  - yarn build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
  local_dir: build
  default_text_charset: "utf-8"
  bucket: "olasso-marketing-site"
  region: ap-southeast-1